### ISSUE TITLE
Break bash kernel out of metakernel and publish separately on PyPI

### ISSUE THREAD

**Issue by blink1073** [Calysto/calysto_bash#1]

**Comment by dsblank** [comment]
Sounds good.... we just need a setup.py (or flit or something) for each kernel, right?

**Comment by blink1073** [comment]
Yep.

**Comment by blink1073** [comment]
(And they can be tested separately using `jupyter_kernel_test`).

**Comment by blink1073** [comment]
Done! https://pypi.python.org/pypi/calysto_bash/0.1.0
